[lint]
select = ["E", "F", "W", "I", "UP", "B"]
ignore = [
    "E501",
    "BLE001",
    "UP041",
    "B008",
    "F401",
]
line-length = 100
target-version = "py310"

[lint.per-file-ignores]
"tests/*" = ["S101", "F401"]
"xping/ping.py" = ["F401"]
"xping/trace.py" = ["F401"]
"xping/lookup.py" = ["F401"]
"xping/tcp.py" = ["F401"]
"xping/portscan.py" = ["F401"]
"xping/sweep.py" = ["F401"]
"xping/ipscan.py" = ["F401"]
