[metadata]
name = xping
version = 1.3.5
author = Mehdi Askari
author_email = iorganamis@gmail.com
description = Beautiful CLI network diagnostics
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
url = https://github.com/mehdiaskari/xping

[options]
packages = find:
python_requires = >=3.10
install_requires =
    certifi

[options.entry_points]
console_scripts =
    xping = xping.__main__:main

[options.packages.find]
include = xping*

[egg_info]
tag_build =
tag_date = 0
